package Model;
// Generated 16/08/2018 21:33:21 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int id;
     private String nome;
     private String cpf;
     private String endereco;

    public Cliente() {
    }

	
    public Cliente(int id) {
        this.id = id;
    }
    public Cliente(int id, String nome, String cpf, String endereco) {
       this.id = id;
       this.nome = nome;
       this.cpf = cpf;
       this.endereco = endereco;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }




}


